Libreria/Models/Editoriale.cs
using System;
using System.Collections.Generic;

namespace Libreria.Models;

public partial class Editoriale
{
    public int Nit { get; set; }

    public string? Nombres { get; set; }

    public string? Telefono { get; set; }

    public string? Direccion { get; set; }

    public string? Email { get; set; }

    public string? Sitioweb { get; set; }

    public virtual ICollection<Libro> Libros { get; set; } = new List<Libro>();
}

Libreria/Controllers/EditorialesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Libreria.Models;

namespace Libreria.Controllers
{
    public class EditorialesController : Controller
    {
        private readonly LibreriaContext _context;

        public EditorialesController(LibreriaContext context)
        {
            _context = context;
        }

        // GET: Editoriales
        public async Task<IActionResult> Index()
        {
            return View(await _context.Editoriales.ToListAsync());
        }

        // GET: Editoriales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editoriale = await _context.Editoriales
                .FirstOrDefaultAsync(m => m.Nit == id);
            if (editoriale == null)
            {
                return NotFound();
            }

            return View(editoriale);
        }

        // GET: Editoriales/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Editoriales/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nit,Nombres,Telefono,Direccion,Email,Sitioweb")] Editoriale editoriale)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(editoriale);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "¡Editorial creada con éxito!" });
                }
                catch (Exception ex)
                {
                    var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                    return Json(new { success = false, message = innerExceptionMessage });
                }
            }
            return Json(new { success = false, message = "Datos del modelo no válidos." });
        }


        // GET: Editoriales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editoriale = await _context.Editoriales.FindAsync(id);
            if (editoriale == null)
            {
                return NotFound();
            }
            return View(editoriale);
        }

        // POST: Editoriales/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Nit,Nombres,Telefono,Direccion,Email,Sitioweb")] Editoriale editoriale)
        {
            if (id != editoriale.Nit)
            {
                return Json(new { success = false, message = "El ID de la editorial no coincide." });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(editoriale);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "¡Editorial editada con éxito!" });
                }
                catch (Exception ex)
                {
                    var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                    return Json(new { success = false, message = innerExceptionMessage });
                }
            }
            return Json(new { success = false, message = "Datos del modelo no válidos." });
        }


        // GET: Editoriales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var editoriale = await _context.Editoriales
                .FirstOrDefaultAsync(m => m.Nit == id);
            if (editoriale == null)
            {
                return NotFound();
            }

            return View(editoriale);
        }

        // POST: Editoriales/DeleteConfirmed/5
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var Editorial = await _context.Editoriales.FindAsync(id);
                if (Editorial != null)
                {
                    _context.Editoriales.Remove(Editorial);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true });
                }
                return Json(new { success = false, message = "Registro no encontrado" });
            }
            catch (DbUpdateException dbEx)
            {
                // Verifica si la excepción es causada por una restricción de clave foránea
                if (dbEx.InnerException != null && dbEx.InnerException.Message.Contains("REFERENCE constraint"))
                {
                    return Json(new { success = false, message = "No se puede eliminar el registro porque está siendo referenciado en otra parte del sistema." });
                }
                // En otros casos, devuelve un mensaje genérico
                return Json(new { success = false, message = "Ocurrió un error al eliminar el registro. Por favor, inténtalo de nuevo más tarde." });
            }
            catch (Exception ex)
            {
                // Maneja otras excepciones
                var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                return Json(new { success = false, message = innerExceptionMessage });
            }
        }


        private bool EditorialeExists(int id)
        {
            return _context.Editoriales.Any(e => e.Nit == id);
        }
    }
}

Libreria/Views/Editoriales/Create.cshtml
@model Libreria.Models.Editoriale

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Registrar Editorial</h1>
<hr />
<div class="form-container">
    <div class="col-md-4 form-background">
        <form id="createEditorialForm" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sitioweb" class="control-label"></label>
                <input asp-for="Sitioweb" class="form-control" />
                <span asp-validation-for="Sitioweb" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between">
                <input type="submit" value="Registrar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js"></script>
    <script>
        handleFormSubmit('#createEditorialForm', '@Url.Action("Index", "Editoriales")');
    </script>
}

Libreria/Views/Editoriales/Details.cshtml
@model Libreria.Models.Editoriale

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center">Detalles de Editorial</h1>

<div class="form-container">
    <div class="col-md-4 form-background">
        <h4 class="text-center">Editorial</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4 control-label">
                @Html.DisplayNameFor(model => model.Nombres)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Nombres)
            </dd>
            <dt class="col-sm-4 control-label">
                @Html.DisplayNameFor(model => model.Telefono)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Telefono)
            </dd>
            <dt class="col-sm-4 control-label">
                @Html.DisplayNameFor(model => model.Direccion)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Direccion)
            </dd>
            <dt class="col-sm-4 control-label">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-4 control-label">
                @Html.DisplayNameFor(model => model.Sitioweb)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Sitioweb)
            </dd>
        </dl>
        <div class="d-flex justify-content-end">
            <a asp-action="Edit" asp-route-id="@Model?.Nit" class="btn btn-info">Editar</a>
            <a asp-action="Index" class="btn btn-secondary">Volver</a>
        </div>
    </div>
</div>

Libreria/Views/Editoriales/Edit.cshtml
@model Libreria.Models.Editoriale

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Editar Editorial</h1>
<hr />
<div class="form-container">
    <div class="col-md-4 form-background">
        <form id="editEditorialForm" asp-action="Edit" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Nit" />
            <div class="form-group">
                <label asp-for="Nombres" class="control-label"></label>
                <input asp-for="Nombres" class="form-control" />
                <span asp-validation-for="Nombres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sitioweb" class="control-label"></label>
                <input asp-for="Sitioweb" class="form-control" />
                <span asp-validation-for="Sitioweb" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js"></script>
    <script>
        handleFormSubmit('#editEditorialForm', '@Url.Action("Index", "Editoriales")');
    </script>
}

Libreria/Views/Editoriales/Index.cshtml
@model IEnumerable<Libreria.Models.Editoriale>

@{
    ViewData["Title"] = "Index";
}

<h1>Editoriales</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Registrar</a>
</p>
@Html.AntiForgeryToken()
<table class="table" id="Editoriales">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nombres)</th>
            <th>@Html.DisplayNameFor(model => model.Telefono)</th>
            <th>@Html.DisplayNameFor(model => model.Direccion)</th>
            <th>@Html.DisplayNameFor(model => model.Email)</th>
            <th>@Html.DisplayNameFor(model => model.Sitioweb)</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nombres)</td>
                <td>@Html.DisplayFor(modelItem => item.Telefono)</td>
                <td>@Html.DisplayFor(modelItem => item.Direccion)</td>
                <td>@Html.DisplayFor(modelItem => item.Email)</td>
                <td>@Html.DisplayFor(modelItem => item.Sitioweb)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Nit" class="btn btn-sm btn-info">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.Nit" class="btn btn-sm btn-warning">Detalles</a>
                    <a href="javascript:void(0);" onclick="confirmDelete('@Url.Action("DeleteConfirmed", "Editoriales", new { id = item.Nit })', this)" class="btn btn-sm btn-danger">Borrar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="~/js/site.js"></script>
<script>
    createDataTable("Editoriales");
</script>