Libreria/Models/LibrosAutor.cs
using System;
using System.Collections.Generic;

namespace Libreria.Models;

public partial class LibrosAutor
{
    public int Id { get; set; }

    public int? IdLibro { get; set; }

    public int? IdAutor { get; set; }

    public virtual Autor? IdAutorNavigation { get; set; }

    public virtual Libro? IdLibroNavigation { get; set; }
}

Libreria/Controllers/LibrosAutorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Libreria.Models;

namespace Libreria.Controllers
{
    public class LibrosAutorsController : Controller
    {
        private readonly LibreriaContext _context;

        public LibrosAutorsController(LibreriaContext context)
        {
            _context = context;
        }

        // GET: LibrosAutors
        public async Task<IActionResult> Index()
        {
            var libreriaContext = _context.LibrosAutors.Include(l => l.IdAutorNavigation).Include(l => l.IdLibroNavigation);
            return View(await libreriaContext.ToListAsync());
        }

        // GET: LibrosAutors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var librosAutor = await _context.LibrosAutors
                .Include(l => l.IdAutorNavigation)
                .Include(l => l.IdLibroNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (librosAutor == null)
            {
                return NotFound();
            }

            return View(librosAutor);
        }

        // GET: LibrosAutors/Create
        public IActionResult Create()
        {
            ViewData["IdAutor"] = new SelectList(_context.Autors, "IdAutor", "IdAutor");
            ViewData["IdLibro"] = new SelectList(_context.Libros, "Isbn", "Isbn");
            return View();
        }

        // POST: LibrosAutors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,IdLibro,IdAutor")] LibrosAutor librosAutor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(librosAutor);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "¡Asociación de libro y autor creada con éxito!" });
                }
                catch (Exception ex)
                {
                    var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                    return Json(new { success = false, message = innerExceptionMessage });
                }
            }
            return Json(new { success = false, message = "Datos del modelo no válidos." });
        }


        // GET: LibrosAutors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var librosAutor = await _context.LibrosAutors.FindAsync(id);
            if (librosAutor == null)
            {
                return NotFound();
            }
            ViewData["IdAutor"] = new SelectList(_context.Autors, "IdAutor", "IdAutor", librosAutor.IdAutor);
            ViewData["IdLibro"] = new SelectList(_context.Libros, "Isbn", "Isbn", librosAutor.IdLibro);
            return View(librosAutor);
        }

        // POST: LibrosAutors/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,IdLibro,IdAutor")] LibrosAutor librosAutor)
        {
            if (id != librosAutor.Id)
            {
                return Json(new { success = false, message = "El ID de la asociación no coincide." });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(librosAutor);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "¡Asociación de libro y autor editada con éxito!" });
                }
                catch (Exception ex)
                {
                    var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                    return Json(new { success = false, message = innerExceptionMessage });
                }
            }
            return Json(new { success = false, message = "Datos del modelo no válidos." });
        }

        // GET: LibrosAutors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var librosAutor = await _context.LibrosAutors
                .Include(l => l.IdAutorNavigation)
                .Include(l => l.IdLibroNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (librosAutor == null)
            {
                return NotFound();
            }

            return View(librosAutor);
        }

        // POST: LibrosAutors/DeleteConfirmed/5
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var LibroAutor = await _context.LibrosAutors.FindAsync(id);
                if (LibroAutor != null)
                {
                    _context.LibrosAutors.Remove(LibroAutor);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true });
                }
                return Json(new { success = false, message = "Registro no encontrado" });
            }
            catch (DbUpdateException dbEx)
            {
                // Verifica si la excepción es causada por una restricción de clave foránea
                if (dbEx.InnerException != null && dbEx.InnerException.Message.Contains("REFERENCE constraint"))
                {
                    return Json(new { success = false, message = "No se puede eliminar el registro porque está siendo referenciado en otra parte del sistema." });
                }
                // En otros casos, devuelve un mensaje genérico
                return Json(new { success = false, message = "Ocurrió un error al eliminar el registro. Por favor, inténtalo de nuevo más tarde." });
            }
            catch (Exception ex)
            {
                // Maneja otras excepciones
                var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                return Json(new { success = false, message = innerExceptionMessage });
            }
        }

        private bool LibrosAutorExists(int id)
        {
            return _context.LibrosAutors.Any(e => e.Id == id);
        }
    }
}

Libreria/Views/LibrosAutors/Create.cshtml
@model Libreria.Models.LibrosAutor

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Asociar Libro y Autor</h1>
<hr />
<div class="form-container">
    <div class="col-md-4 form-background">
        <form id="createLibroAutorForm" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdLibro" class="control-label"></label>
                <select asp-for="IdLibro" class="form-control" asp-items="ViewBag.IdLibro"></select>
            </div>
            <div class="form-group">
                <label asp-for="IdAutor" class="control-label"></label>
                <select asp-for="IdAutor" class="form-control" asp-items="ViewBag.IdAutor"></select>
            </div>
            <div class="form-group d-flex justify-content-between">
                <input type="submit" value="Asociar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js"></script>
    <script>
        handleFormSubmit('#createLibroAutorForm', '@Url.Action("Index", "LibrosAutors")');
    </script>
}

Libreria/Views/LibrosAutors/Details.cshtml
@model Libreria.Models.LibrosAutor

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center">Detalles</h1>

<div class="form-container">
    <div class="col-md-4 form-background">
        <h4 class="text-center">LibrosAutor</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4 control-label">
                Autor
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.IdAutorNavigation.IdAutor)
            </dd>
            <dt class="col-sm-4 control-label">
                Libro
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.IdLibroNavigation.Isbn)
            </dd>
        </dl>
        <div class="d-flex justify-content-end">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-info">Editar</a>
            <a asp-action="Index" class="btn btn-secondary">Volver</a>
        </div>
    </div>
</div>

Libreria/Views/LibrosAutors/Edit.cshtml
@model Libreria.Models.LibrosAutor

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Editar</h1>
<hr />
<div class="form-container">
    <div class="col-md-4 form-background">
        <form id="editLibroAutorForm" asp-action="Edit" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="IdLibro" class="control-label"></label>
                <select asp-for="IdLibro" class="form-control" asp-items="ViewBag.IdLibro"></select>
                <span asp-validation-for="IdLibro" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdAutor" class="control-label"></label>
                <select asp-for="IdAutor" class="form-control" asp-items="ViewBag.IdAutor"></select>
                <span asp-validation-for="IdAutor" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js"></script>
    <script>
        handleFormSubmit('#editLibroAutorForm', '@Url.Action("Index", "LibrosAutors")');
    </script>
}

Libreria/Views/LibrosAutors/Index.cshtml
@model IEnumerable<Libreria.Models.LibrosAutor>

@{
    ViewData["Title"] = "Index";
}

<h1>Libros y Autores</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Asociar</a>
</p>
@Html.AntiForgeryToken()
<table class="table" id="LibrosAutor">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdAutorNavigation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdLibroNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.Raw($"{item.IdAutorNavigation.Nombre} {item.IdAutorNavigation.Apellido}")
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdLibroNavigation.Titulo)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-info">Editar</a> 
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Detaller</a> 
                    <a href="javascript:void(0);" onclick="confirmDelete('@Url.Action("DeleteConfirmed", "LibrosAutors", new { id = item.Id })', this)" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="~/js/site.js"></script>
<script>
    createDataTable("LibrosAutor");
</script>