Libreria/Models/Categoria.cs
using System;
using System.Collections.Generic;

namespace Libreria.Models;

public partial class Categoria
{
    public int CodigoCategoria { get; set; }

    public string? Nombre { get; set; }

    public virtual ICollection<Libro> Libros { get; set; } = new List<Libro>();
}

Libreria/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Libreria.Models;

namespace Libreria.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly LibreriaContext _context;

        public CategoriasController(LibreriaContext context)
        {
            _context = context;
        }

        // GET: Categorias
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categorias.ToListAsync());
        }

        // GET: Categorias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias
                .FirstOrDefaultAsync(m => m.CodigoCategoria == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categorias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodigoCategoria,Nombre")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Add(categoria);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "¡Categoría creada con éxito!" });
                }
                catch (Exception ex)
                {
                    var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                    return Json(new { success = false, message = innerExceptionMessage });
                }
            }
            return Json(new { success = false, message = "Datos del modelo no válidos." });
        }


        // GET: Categorias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodigoCategoria,Nombre")] Categoria categoria)
        {
            if (id != categoria.CodigoCategoria)
            {
                return Json(new { success = false, message = "El ID de la categoría no coincide." });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true, message = "¡Categoría editada con éxito!" });
                }
                catch (Exception ex)
                {
                    var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                    return Json(new { success = false, message = innerExceptionMessage });
                }
            }
            return Json(new { success = false, message = "Datos del modelo no válidos." });
        }


        // GET: Categorias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categorias
                .FirstOrDefaultAsync(m => m.CodigoCategoria == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categorias/DeleteConfirmed/5
        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var Categoria = await _context.Categorias.FindAsync(id);
                if (Categoria != null)
                {
                    _context.Categorias.Remove(Categoria);
                    await _context.SaveChangesAsync();
                    return Json(new { success = true });
                }
                return Json(new { success = false, message = "Registro no encontrado" });
            }
            catch (DbUpdateException dbEx)
            {
                // Verifica si la excepción es causada por una restricción de clave foránea
                if (dbEx.InnerException != null && dbEx.InnerException.Message.Contains("REFERENCE constraint"))
                {
                    return Json(new { success = false, message = "No se puede eliminar el registro porque está siendo referenciado en otra parte del sistema." });
                }
                // En otros casos, devuelve un mensaje genérico
                return Json(new { success = false, message = "Ocurrió un error al eliminar el registro. Por favor, inténtalo de nuevo más tarde." });
            }
            catch (Exception ex)
            {
                // Maneja otras excepciones
                var innerExceptionMessage = ex.InnerException != null ? ex.InnerException.Message : ex.Message;
                return Json(new { success = false, message = innerExceptionMessage });
            }
        }

        private bool CategoriaExists(int id)
        {
            return _context.Categorias.Any(e => e.CodigoCategoria == id);
        }
    }
}

Libreria/Views/Categorias/Create.cshtml
@model Libreria.Models.Categoria

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-center">Registrar Categoria</h1>
<hr />
<div class="form-container">
    <div class="col-md-4 form-background">
        <form id="createCategoriaForm" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between">
                <input type="submit" value="Registrar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js"></script>
    <script>
        handleFormSubmit('#createCategoriaForm', '@Url.Action("Index", "Categorias")');
    </script>
}

Libreria/Views/Categorias/Details.cshtml
@model Libreria.Models.Categoria

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-center">Detalles de Categoría</h1>

<div class="form-container">
    <div class="col-md-4 form-background">
        <h4 class="text-center">Categoría</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4 control-label">
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
            <dd class="col-sm-8">
                @Html.DisplayFor(model => model.Nombre)
            </dd>
        </dl>
        <div class="d-flex justify-content-end">
            <a asp-action="Edit" asp-route-id="@Model?.CodigoCategoria" class="btn btn-info">Editar</a>
            <a asp-action="Index" class="btn btn-secondary">Volver</a>
        </div>
    </div>
</div>

Libreria/Views/Categorias/Edit.cshtml
@model Libreria.Models.Categoria

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center">Editar Categoria</h1>
<hr />
<div class="form-container">
    <div class="col-md-4 form-background">
        <form id="editCategoriaForm" asp-action="Edit" method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CodigoCategoria" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between">
                <input type="submit" value="Guardar" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary">Volver</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js"></script>
    <script>
        handleFormSubmit('#editCategoriaForm', '@Url.Action("Index", "Categorias")');
    </script>
}

Libreria/Views/Categorias/Index.cshtml
@model IEnumerable<Libreria.Models.Categoria>

@{
    ViewData["Title"] = "Index";
}

<h1>Categorias</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Registrar</a>
</p>
@Html.AntiForgeryToken()
<table class="table" id="Categorias">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Nombre)</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.CodigoCategoria" class="btn btn-sm btn-info">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.CodigoCategoria" class="btn btn-sm btn-warning">Detalles</a>
                    <a href="javascript:void(0);" onclick="confirmDelete('@Url.Action("DeleteConfirmed", "Categorias", new { id = item.CodigoCategoria })', this)" class="btn btn-sm btn-danger">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="~/js/site.js"></script>
<script>
    createDataTable("Categorias");
</script>